### ISSUE TITLE
Add example for port forwarding

### ISSUE THREAD

**Issue by egee-irl** [Oefenweb/ansible-ufw#25]
The examples in the readme are quite good, however there is not an example that features Port Forwarding.

It would be great for folks looking for a comprehensive ufw role that supports port forwarding to see one in the examples because it is not clear from the readme if this role supports it.

**Comment by tersmitten** [comment]
I have no idea too, do you have a `terminal` (or generic `ansible`) example?

**Comment by oneslash** [comment]
I have managed to do it with

```yml
- name: insert port forwarding for ufw
  lineinfile:
    dest: /etc/ufw/before.rules
    line: "{{ item }}"
  with_items:
    - '*nat'
    - ':POSTROUTING ACCEPT [0:0]'
    - "-A POSTROUTING -s {{  }} -o ens5 -j MASQUERADE \nCOMMIT"
```
