### ISSUE TITLE
Loops not supported

### ISSUE THREAD

**Issue by niftylettuce** [Oefenweb/ansible-ufw#41]
This does not work (it will only honor the last `ufw_rules` block).  Thus I just got locked out of a freshly provisioned server:

```yml
---
- import_playbook: security.yml hostlist=redis
- hosts: redis
  become: true
  become_user: root
  roles:
    # https://github.com/Oefenweb/ansible-ufw
    - role: ufw
      ufw_rules:
        - rule: allow
          to_port: 22
          protocol: tcp
          comment: ssh
  tasks:
    - name: loop over ufw
      include_role:
        name: ufw
      vars:
        ufw_rules:
          - rule: allow
            to_port: "{{ lookup('env', 'REDIS_PORT') }}"
            from_ip: "{{ item }}"
            protocol: tcp
            comment: "redis access from {{ item }}"
      with_items: "{{ groups['web'] + groups['api'] + groups['bull'] }}"
```
